### PR TITLE
detection for hp-ux machine

### PR DESCRIPTION
**Pull request by Anirudh-Gupta**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chris-rock** [comment]
Hi @Anirudh-Gupta, this is an awesome addition. This looks really good. Once we cleared out the style issues, I am happy to merge.

**Comment by Anirudh-Gupta** [comment]
@chris-rock rubocop issues have been fixed and travis-ci passes now.

**Comment by chris-rock** [comment]
Awesome! Thanks @Anirudh-Gupta

**Comment by chris-rock** [comment]
This is an obvious fix as defined in https://github.com/chef/chef/blob/master/CONTRIBUTING.md

@Anirudh-Gupta could you please sign the CLA as well?

**Pull request merged**
