### PR TITLE
feature: add file.basename

### PR DESCRIPTION
**Pull request by arlimus**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @arlimus

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by srenatus** [comment]
Hmm... we could have employed [`Pathname`](http://ruby-doc.org/stdlib-1.9.3/libdoc/pathname/rdoc/Pathname.html), couldn't we?

> It does not represent the file itself. A Pathname can be relative or absolute. It’s not until you try to reference the file that it even matters whether the file exists or not.

**Comment by arlimus** [comment]
@srenatus basename for `Pathname` defaults to the running system's separator. When we are targeting a remote system, that might be local=Unix vs remote=Windows. Afaics, pathname doesn't provide us with a configurable separator. The docs point from Pathname.basename to File.basename:

```
See File.basename. Returns the last component of the path.
```

which in turn:

```
Returns the last component of the filename given in file_name, which can be formed using both File::SEPARATOR and File::ALT_SEPARATOR as the separator when File::ALT_SEPARATOR is not nil. If suffix is given and present at the end of file_name, it is removed. If suffix is “.*”, any extension will be removed.
```

Try:

```
Pathname.new('C:\hello\world').basename
```

**Comment by arlimus** [comment]
Unless you know how to do that?

**Comment by srenatus** [comment]
Nah, you're right. I mistook the "suffix" thing for the ability to pass a separator :/

Can't even get `Pathname` work when I override `File::SEPARATOR`...

**Comment by arlimus** [comment]
Oh wow, I was expecting it to work at least that far... well, really hate to duplicate code, but ... :hamster:

**Comment by chris-rock** [comment]
Thanks for this feature @arlimus

**Pull request merged**
