### PR TITLE
activate integration tests in travis

### PR DESCRIPTION
**Pull request by chris-rock**

### CODE REVIEW

**Comment by arlimus** [comment]
Travis is at your service :grinning: 
Go go travis

**Comment by srenatus** [comment]
Hmm. Fails on my machine:

```
$ bundle install --binstubs=.bin
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "httpclient":
  In snapshot (Gemfile.lock):
    httpclient (= 2.7.0.1)

  In Gemfile:
    r-train (>= 0) ruby depends on
      winrm-transport (~> 1.0) ruby depends on
        winrm (~> 1.3) ruby depends on
          httpclient (>= 2.2.0.2, ~> 2.2) ruby

    berkshelf (~> 4.0) ruby depends on
      httpclient (~> 2.6.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by arlimus** [comment]
@srenatus very strange, it works on my node. what ruby are you on?

**Comment by srenatus** [comment]
@arlimus ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

**Comment by arlimus** [comment]
@srenatus now that's strange, here's mine: `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]`

**Comment by chris-rock** [comment]
@srenatus try to remove your `gemfile.lock`

**Comment by srenatus** [comment]
@chris-rock yep, solved. thanks.

**Pull request merged**
