### PR TITLE
Attempt to avoid "Preparing modules for first use"

### PR DESCRIPTION
**Pull request by IlyaFinkelshteyn**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @IlyaFinkelshteyn

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by mwrock** [comment]
I agree `-noprofile` is good but might not solve this problem.

You want to make sure scripts are pretended with `$profilepreference = "silentlycontinue"`

**Comment by IlyaFinkelshteyn** [comment]
It is attempt to solve [this](http://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr) issue.  As you see `$profilepreference = "silentlycontinue"` is already set and stopped helping after latest Appveyor VHD updates. Therefore Christoph was needed to go back to previous Appveyor VHD. Adding `-noprofile` actually helps, and all builds are passed OK on the current image (https://ci.appveyor.com/project/IlyaFinkelshteyn/train/build/master-11). With previous image ruby_version=21 fails. 
I am still trying to figure out what exact update broke previous behavior (which did not require `-noprofile`), but I have feeling that it could be Windows update we should not undo.

**Comment by IlyaFinkelshteyn** [comment]
Anyhow I believe that this change together with latest "Visual Studio 2015" image for Appveyor will work OK.

**Comment by mwrock** [comment]
Oh interesting. I do know appveyor added wmf5 to their image about a month ago which broke stuff in this area. I wonder if this is the latest round of "anniversary" updates that's new with P's 5.1.

**Comment by IlyaFinkelshteyn** [comment]
Oh, hopefully I will understand what really happened because now I am suggesting it little blindly...

**Comment by chris-rock** [comment]
@IlyaFinkelshteyn Wouldn't that require us to change reactivate the new image in our appveyor config?

**Comment by IlyaFinkelshteyn** [comment]
Yes, with previous image and `-noprofile` one job fails (both in here PR and for my fork). Honestly still do not know why. New image and `-noprofile` works good.

**Comment by chris-rock** [comment]
This fixes #153

**Comment by chris-rock** [comment]
Thanks @IlyaFinkelshteyn. I ported the `noprofile` options to the latest master. Thanks a lot for highlighting the solution! This PR is superseeded by #152

**Pull request closed without merging**
